export const INFORMATION_TITLE_MAX_LENGTH = 64;
export const INFORMATION_DESCRIPTION_MAX_LENGTH = 512;
export const INFORMATION_MAX_FILE_SIZE = 5000000;
export const INFORMATION_MAX_FAVICON_SIZE = 5000;
